name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build and Deploy Docs
        uses: rakrsh/central-actions/doc-build-deploy@main
        with:
          doc-build-command: 'uv run mkdocs build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
